[package]
name = "twistrs"
version = "0.1.2-beta"
description = "A domain name permutation and enumeration library"
license = "MIT"
repository = "https://github.com/JuxhinDB/twistrs"
documentation  = "https://docs.rs/crate/twistrs"
authors = ["Juxhin Dyrmishi Brigjaj <juxhin@phishdeck.com>"]
edition = "2018"

[dependencies]
publicsuffix = "1.5"
lazy_static  = "1.4.0"
phf	         = { version = "0.8.0", features = ["macros"] }
async-smtp = "0.3.4"
async-native-tls = "0.3.3"
futures = "0.3"
tokio  = { version = "0.2.22", features = ["dns"] }

[build-dependencies]
punycode = "0.4.1"
