[package]
name = "twistrs"
version = "0.2.2-beta"
description = "An asynchronous domain name permutation and enumeration library."
license = "MIT"
repository = "https://github.com/JuxhinDB/twistrs"
documentation  = "https://docs.rs/crate/twistrs"
authors = ["Juxhin Dyrmishi Brigjaj <juxhin@phishdeck.com>"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.playground]
features = ["full"]

[features]
geoip_lookup = [ "maxminddb" ]

[dependencies]
publicsuffix = "1.5"
lazy_static  = "1.4.0"
phf	         = { version = "0.8.0", features = ["macros"] }
async-smtp = "0.3.4"
async-native-tls = "0.3.3"
futures = "0.3"
tokio  = { version = "0.2.22", features = ["dns", "macros"] }
fancy-regex = "0.4.0"
idna = "0.2.0"
hyper = "0.13.8"
maxminddb = { version = "0.15.0", optional = true}
itertools = "0.9.0"

[build-dependencies]
punycode = "0.4.1"
