[package]
name = "twistrs"
version = "0.1.1-beta"
authors = ["Juxhin Dyrmishi Brigjaj <juxhin@phishdeck.com>"]
edition = "2018"

[dependencies]
publicsuffix = "1.5"
lazy_static  = "1.4.0"
phf	         = { version = "0.8.0", features = ["macros"] }
async-smtp = "0.3.4"
async-native-tls = "0.3.3"
futures = "0.3"
tokio  = { version = "0.2.22", features = ["dns"] }
